### PR TITLE
often need git for npm installs

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by timgent** [comment]
LGTM

**Comment by easternbloc** [comment]
not sure this should be in our base image... I'd rather it was in whatever inherits from this.

**Comment by easternbloc** [comment]
@chrisns can I close this based on my comments or would you like to discuss more?

**Comment by chrisns** [comment]
I think it's common enough to warrant being in the base
but happy to go with a group consensus if that is the position that we shouldn't have it in base

**Comment by JoeChapman** [comment]
I'm not sure why anyone would want to have git installed other than to use private github for dependencies, which would require auth. In which case, how would the ssh key be managed?

**Comment by easternbloc** [comment]
Also happy for the general consensus on this.

FWIW I'd rather keep our base images as locked down as possible and let anyone who needs extra features to take that security risk.

**Comment by chrisns** [comment]
i've used it for public things that don't make sense to publish to npm.
e.g. 
https://github.com/ukhomeoffice/removals_schema

**Comment by JoeChapman** [comment]
@chrisns that was definitely an edge-case. I'm for making implementations such as this downstream. I will acquiesce to the groups consensus. But I have cast my vote in favour of out.

**Comment by easternbloc** [comment]
WOW!

**Pull request closed without merging**
